version: "2"
services:
    nats-cli:
        image: natsio/nats-box
        command: tail -f /dev/null
        networks:
            - backend

    nats-server:
        image: nats:2.10-alpine
        command: "--user some_user --pass some_passwd --cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
        networks:
            - backend
        ports:
            - 8222:8222

    nats-1:
        image: nats:2.10-alpine
        command: "--user some_user --pass some_passwd --name nats-1 --cluster_name NATS --js -m 8222 --cluster nats://0.0.0.0:6222 --routes nats://nats-1:6222,nats://nats-2:6222,nats://nats-3:6222 --routes=nats://some_user:some_passwd@nats-server:6222"
        networks:
            - backend
        depends_on:
            - nats-server

    nats-2:
        image: nats:2.10-alpine
        command: "--user some_user --pass some_passwd --name nats-2 --cluster_name NATS --js -m 8222 --cluster nats://0.0.0.0:6222 --routes nats://nats-1:6222,nats://nats-2:6222,nats://nats-3:6222 --routes=nats://some_user:some_passwd@nats-server:6222"
        networks:
            - backend
        depends_on:
            - nats-server

    nats-3:
        image: nats:2.10-alpine
        command: "--user some_user --pass some_passwd --name nats-3 --cluster_name NATS --js -m 8222 --cluster nats://0.0.0.0:6222 --routes nats://nats-1:6222,nats://nats-2:6222,nats://nats-3:6222 --routes=nats://some_user:some_passwd@nats-server:6222"
        networks:
            - backend
        depends_on:
            - nats-server

networks:
  backend:
    driver: bridge

